[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  timeout = 30
  external_node_modules = ["@prisma/client", "@next-auth/prisma-adapter"]